# Generated by Django 4.1 on 2023-03-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snabbfakta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=2083)),
                ('head_quote', models.CharField(max_length=200)),
                ('last_updated', models.CharField(max_length=50)),
                ('quote', models.CharField(max_length=1000)),
                ('quote_sayer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Summary_om_oss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=5000)),
            ],
        ),
    ]
