# Generated by Django 4.1 on 2023-04-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_snabbfakta_summary_om_oss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('front', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=2083)),
                ('summary', models.CharField(max_length=600)),
                ('par_one', models.CharField(max_length=1000)),
                ('par_two', models.CharField(max_length=600)),
                ('par_three', models.CharField(max_length=600)),
                ('par_four', models.CharField(max_length=600)),
                ('par_five', models.CharField(max_length=600)),
                ('par_six', models.CharField(max_length=600)),
                ('par_seven', models.CharField(max_length=600)),
                ('par_eight', models.CharField(max_length=600)),
                ('par_nine', models.CharField(max_length=600)),
                ('par_ten', models.CharField(max_length=600)),
                ('auther', models.CharField(max_length=30)),
                ('author_image', models.CharField(max_length=2083)),
            ],
        ),
        migrations.AlterField(
            model_name='snabbfakta',
            name='last_updated',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='snabbfakta',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
