# Generated by Django 4.1 on 2023-04-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_intervju_alter_snabbfakta_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=2083)),
                ('mail', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='intervju',
            name='par_eight',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='intervju',
            name='par_five',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='intervju',
            name='par_four',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='intervju',
            name='par_nine',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='intervju',
            name='par_one',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='intervju',
            name='par_seven',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='intervju',
            name='par_six',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='intervju',
            name='par_ten',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='intervju',
            name='par_three',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='intervju',
            name='par_two',
            field=models.CharField(max_length=2083),
        ),
    ]
